### ISSUE TITLE
rendering empty line as `<br />`

### ISSUE THREAD

**Issue by cusxio** [lokiuz/redraft#46]
Is there a way to add empty lines as `<br />` tag?

![screen shot 2018-11-23 at 9 13 05 pm](https://user-images.githubusercontent.com/6487613/48945256-9d528880-ef64-11e8-8ada-9fca0e09e2ab.png)

Here's the raw `contentState` for an empty line.
```js
{
  data: {},
  depth: 0,
  entityRanges: [],
  inlineStyleRanges: [],
  key: "4ltcn",
  text: "",
  type: "unstyled"
}
```

I tried to have the following renderer, but it only works in certain cases.

```js
blocks: {
  unstyled: (children, { keys }) =>
    children.map((child, index) => {
      const last = child[child.length - 1];
      const render = last.length === 0 ? [child, <br key={0} />] : child;

      return <div key={keys[index]}>{render}</div>;
    }),
},
```

If it's possible, can you point me to the right direction?

**Comment by lokiuz** [comment]
I'm not sure what inconsistencies are you getting? Seems like you first thing you want to check is that you're not using the cleanup option - that's what causes the behavior in the example.

I tweaked it a little so that an empty line returns just a `<br/>` not wrapped in a `<div>`.
```js
unstyled: (children, { keys }) =>
    children.map((child, index) => {
      const last = child[child.length - 1];
      if (last.length === 0) {
        return <br key={keys[index]} />;
      }
      return <div key={keys[index]}>{child}</div>;
    }),
```

Another solution would be doing something similar to the example:
```js
const addBreaklines = children => children.map(child => [child, <br />]);

blocks = {
  unstyled: (children, { keys }) => <div key={keys[0]}>{addBreaklines(children)}</div>,
}
```
This creates a single `<div>` around all the unstyled blocks and also adds a `<br />` after each block.

**Comment by cusxio** [comment]
ah I see the issue now. I've been adding the line break to the `children`'s `children`, instead of the `children`.

No wonder it created some issues with the styles clashing with other `entities`.
